<?php

declare(strict_types=1);

namespace Drupal\Tests\Driver\Kernel\Core\Field;

use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Driver\Core\Core;
use Drupal\Driver\Core\Field\DefaultHandler;
use PHPUnit\Framework\Attributes\Group;

/**
 * Coverage test: every known field type is handled or explicitly skipped.
 *
 * Enumerates every field-type plugin the loaded modules expose and asserts
 * that each one is either:
 *   (a) backed by a dedicated handler registered with Core (the registry map
 *       has an entry for this type), or
 *   (b) safe for DefaultHandler - every stored property is a plain scalar the
 *       default can relay verbatim (no entity-reference target, datetime
 *       string, or complex/nested value), or
 *   (c) documented in the SKIP map with a reason (computed, write-only, or
 *       otherwise not stub-expansion-compatible).
 *
 * If a type falls into none of these buckets the test fails with the type
 * name, forcing the contributor to add a handler, confirm DefaultHandler is
 * safe, or record a SKIP entry with a reason. This is the safety net that
 * catches missing-handler regressions before they ship to consumers.
 *
 * @group fields
 */
#[Group('fields')]
class FieldTypeCoverageKernelTest extends FieldHandlerKernelTestBase {

  /**
   * {@inheritdoc}
   *
   * @var array<string>
   */
  protected static $modules = [
    ...self::BASE_MODULES,
    'text',
    'filter',
    'link',
    'datetime',
    'datetime_range',
    'file',
    'image',
    'options',
    'telephone',
    'comment',
    'path',
    'taxonomy',
  ];

  /**
   * Field types that are not eligible for driver expand().
   *
   * Each entry documents the reason so the skip list does not become a
   * silent hiding place for regressions.
   *
   * @var array<string, string>
   */
  private const SKIP = [
    'password' => 'Write-only field; hashed by the user storage layer on save.',
    'comment' => 'Composite field driven by the comment module lifecycle; not stub-expandable.',
    'path' => 'Computed from the path_alias table; stubbing the value has no storage effect.',
    'uuid' => 'Base computed field generated by entity storage; never a stub target.',
    'map' => 'Stores a serialized PHP array in a single value column; scenario authors pass the array directly, so DefaultHandler is bypassed at expand time.',
    'language' => 'Set via the language manager, not via expand(); stub property flows untouched.',
    'shape' => 'Test-only fixture field type shipped by entity_test; not present in production Drupal installs.',
    'shape_required' => 'Test-only fixture field type shipped by entity_test; not present in production Drupal installs.',
  ];

  /**
   * Tests that every known field type has a coverage strategy.
   */
  public function testEveryKnownFieldTypeIsHandledOrSkipped(): void {
    $definitions = \Drupal::service('plugin.manager.field.field_type')->getDefinitions();

    $missing = [];

    foreach (array_keys($definitions) as $type) {
      if (array_key_exists($type, self::SKIP)) {
        continue;
      }

      if ($this->isHandlerRegistered($type)) {
        continue;
      }

      if ($this->isDefaultHandlerSafe($type)) {
        continue;
      }

      $missing[] = $type;
    }

    $this->assertSame(
      [],
      $missing,
      sprintf(
        "Field types with no handler and no SKIP entry: %s.\n"
        . 'Add a dedicated handler under src/Drupal/Driver/Core/Field/ (named <Type>Handler.php), '
        . 'or add a SKIP entry with a documented reason.',
        implode(', ', $missing),
      ),
    );
  }

  /**
   * Returns TRUE when Core has a handler class registered for this type.
   */
  private function isHandlerRegistered(string $type): bool {
    $property = new \ReflectionProperty(Core::class, 'fieldHandlers');
    $handlers = $property->getValue($this->core);

    return isset($handlers[$type]);
  }

  /**
   * Returns TRUE when the field type can ride DefaultHandler's pass-through.
   *
   * DefaultHandler relays a field verbatim only when every stored property is
   * a plain scalar. A property that needs translation (an entity-reference
   * target, a datetime string, a complex/nested value) triggers a loud throw
   * at expand() time, meaning the type needs a dedicated handler.
   */
  private function isDefaultHandlerSafe(string $type): bool {
    try {
      $storage = BaseFieldDefinition::create($type);
      $reason = DefaultHandler::unsupportedPropertyReason($storage);
    }
    catch (\Throwable) {
      // Property construction fails for types that require settings we haven't
      // supplied (e.g. entity_reference without target_type). Treat those as
      // unsafe: if DefaultHandler cannot reason about the properties, neither
      // can this coverage test, and a dedicated handler is the right answer.
      return FALSE;
    }

    return $reason === NULL;
  }

  /**
   * Guards against DefaultHandler being mistakenly matched as a "handler".
   *
   * The handler registry never lists DefaultHandler explicitly (it is the
   * fallback). If this assumption ever changes, isHandlerRegistered() above
   * would falsely mark the DefaultHandler-safe types as "handled", hiding
   * real gaps.
   */
  public function testDefaultHandlerIsNotRegistered(): void {
    $property = new \ReflectionProperty(Core::class, 'fieldHandlers');
    $handlers = $property->getValue($this->core);

    $this->assertNotContains(
      DefaultHandler::class,
      $handlers,
      'DefaultHandler must remain the unregistered fallback.',
    );
  }

}
