name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: PHP ${{ matrix.php_version }}, Drupal ${{ matrix.drupal_version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - php_version: '8.2'
            drupal_version: '10'
          - php_version: '8.3'
            drupal_version: '10'
          - php_version: '8.3'
            drupal_version: '11'
          - php_version: '8.4'
            drupal_version: '10'
          - php_version: '8.4'
            drupal_version: '11'

    env:
      PHP_VERSION: ${{ matrix.php_version }}
      DRUPAL_VERSION: ${{ matrix.drupal_version }}
      DOCKER_USER_ID: '1001'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Start Docker containers
        run: docker compose up -d

      - name: Configure git safe directory
        run: docker compose exec -T php git config --global --add safe.directory /var/www/html

      - name: Update Composer
        run: docker compose exec -T php composer self-update

      - name: Install Composer dependencies
        run: docker compose exec -T php composer install

      - name: Check composer.json is normalized
        run: docker compose exec -T php composer normalize --dry-run

      - name: Add Drupal core dependency
        run: docker compose exec -u ${DOCKER_USER_ID} -T php composer require --no-interaction --dev --no-update drupal/core:^${DRUPAL_VERSION} drupal/core-composer-scaffold:^${DRUPAL_VERSION}

      - name: Update Composer dependencies
        run: docker compose exec -T php composer update --with-all-dependencies

      - name: Migrate PHPUnit configuration
        run: docker compose exec -T php phpunit --migrate-configuration
        if: "${{ matrix.drupal_version == '11'}}"

      - name: Run tests
        run: docker compose exec -T php composer test
